### PR TITLE
Dont restart auditd when augenrules exists

### PR DESCRIPTION
**Pull request by janorn**
Why restart auditd when augenrules has loaded the rules?

### CODE REVIEW

**Comment by juju4** [comment]
Just tested it on Ubuntu 18.04 and augenrules only merged rules.d.
had to call with --load to load into kernel which is not default.

same when checking man page.
http://man7.org/linux/man-pages/man8/augenrules.8.html

also augenrules seems both on redhat and debian/ubuntu
https://centos.pkgs.org/8/centos-baseos-x86_64/audit-3.0-0.10.20180831git0047a6c.el8.x86_64.rpm.html
https://packages.ubuntu.com/bionic/amd64/auditd/filelist

In which environment did you test?

**Comment by janorn** [comment]
You are right. I failed to notice that the command didn't do load. Added this to the PR. Doing so many reboots so missed this part .... oops ....

**Comment by janorn** [comment]
I add --load any thought on this?

**Comment by juju4** [comment]
Sorry for delay. seems good

**Comment by juju4** [comment]
for some reason, this fails in travis-ci
https://travis-ci.com/github/juju4/ansible-auditd/jobs/401402630#L13166

can you review?

**Comment by juju4** [comment]
is this still relevant or can it be closed?

**Comment by juju4** [comment]
Closing as old and no updates

**Pull request closed without merging**
