### PR TITLE
Simplify distribution handling

### PR DESCRIPTION
**Pull request by j8r**
There aren't any difference between the versions of a same distribution.
The actual logic prevents us to use other versions of a distribution without creating a new variable file, like `vars/Debian-10.yml` or `vars/Ubuntu-18.10.yml`, which are exactly the same than other files.

### CODE REVIEW

**Comment by juju4** [comment]
ok for vars distribution file.

Can you develop on augenrules? which distribution/release where problematic?
my main focus is usually ubuntu+centos LTS and both have augenrules in auditd package
https://centos.pkgs.org/7/centos-x86_64/audit-2.8.4-4.el7.x86_64.rpm.html
https://centos.pkgs.org/6/centos-i386/audit-2.4.5-6.el6.i686.rpm.html
https://packages.ubuntu.com/bionic/amd64/auditd/filelist
https://packages.ubuntu.com/xenial/amd64/auditd/filelist

also missing a name update of augenrules stat.
In general, would prefer in different PR but ok to keep as is for this one.
Thanks

**Comment by j8r** [comment]
Alpine doens't have it, and older systems like Debian Jessie, which is still supported

**Comment by j8r** [comment]
Alpine doesn't have it, and older systems like Debian Jessie, which is still supported

**Comment by juju4** [comment]
sadly as auditd is kernel stuff, not much automated testing we can add at least in containers.
but please add alpine+debian entries to .kitchen.vagrant.yml

**Comment by j8r** [comment]
There is no bento platform for Alpine, I think Debian is enough.

**Comment by j8r** [comment]
Hum wait, what's the purpose of `templates/audit.rules.j2`, which group all other templates?! This file isn't actually used, but there is a huge comment about it.

**Comment by juju4** [comment]
audit.rules.j2 is a remnant of previous setup with just one file.
Else LGTM.
Thanks!

**Pull request merged**
